require 'nokogiri'
require 'net/http'
require 'uri'
require 'json'
require 'open-uri'

require_relative '../lib/artificially_colored/scraper'
require_relative '../lib/artificially_colored/ai'
require_relative '../lib/artificially_colored/cli'
require_relative '../lib/artificially_colored/version'